name: CI_Builder

# this file creates the final suvriddhi release for updates
on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest-arm64
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install linux deps
                        run: |
                            sudo apt-get update
                            sudo apt-get install -y build-essential libcivetweb-dev clang-format

            - name: Install dependencies (Physics)
              run: |
                  cd src_phy
                  npm ci

            - name: Install dependencies (CS)
              run: |
                  cd src_cs
                  npm ci

            - name: Install dependencies (Home)
              run: |
                  cd home
                  npm ci

            - name: Make release directory structure
              run: |
                  mkdir $GITHUB_WORKSPACE/release
                  mkdir $GITHUB_WORKSPACE/release/build
                  mkdir $GITHUB_WORKSPACE/release/learn
                  mkdir $GITHUB_WORKSPACE/release/etc

            - name: Build Physics
              run: |
                  cd src_phy
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/learn/

            - name: Audit Physics
              run: |
                  cd src_phy
                  npm audit --audit-level=critical

            - name: Build CS
              run: |
                  cd src_cs
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/build/

            - name: Audit CS
              run: |
                  cd src_cs
                  npm audit --audit-level=critical

            - name: Build Home
              run: |
                  cd home
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/

            - name: Audit Home
              run: |
                  cd home
                  npm audit --audit-level=critical

            - name: Add init.d directory
              run: |
                  cd board/raspberrypi/rootfs-overlay/etc
                  cp -r * $GITHUB_WORKSPACE/release/etc

            - name: Add compiled backend
              run: |
                  cd src_cs/backend
                  make
                  cp server $GITHUB_WORKSPACE/release/

            - name: Compress out directory
              run: |
                  cd $GITHUB_WORKSPACE/release
                  zip -r $GITHUB_WORKSPACE/suvriddhi.zip .

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: build-${{ github.run_number }}
                  name: Build ${{ github.run_number }}
                  files: suvriddhi.zip
                  token: ${{ secrets.GITHUB_TOKEN }}
