name: CI_Builder

# this file creates the final suvriddhi release for updates
on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install books
              run: |
                  cd src_phy/public/pdfs
                  wget https://github.com/LearnPRG-py/SuvriddhiBooks/releases/download/book/drive-download-20260617T081439Z-3-001.zip
                  unzip drive-download-20260617T081439Z-3-001.zip "*" -d .
                  rm drive-download-20260617T081439Z-3-001.zip

            - name: Install dependencies (Physics)
              run: |
                  cd src_phy
                  npm ci

            - name: Install dependencies (CS)
              run: |
                  cd src_cs
                  npm ci

            - name: Install dependencies (Home)
              run: |
                  cd home
                  npm ci

            - name: Make release directory structure
              run: |
                  mkdir $GITHUB_WORKSPACE/release
                  mkdir $GITHUB_WORKSPACE/release/build
                  mkdir $GITHUB_WORKSPACE/release/learn

            - name: Build Physics
              run: |
                  cd src_phy
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/learn/

            - name: Audit Physics
              run: |
                  cd src_phy
                  npm audit --audit-level=critical

            - name: Build CS
              run: |
                  cd src_cs
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/build/

            - name: Audit CS
              run: |
                  cd src_cs
                  npm audit --audit-level=critical

            - name: Build Home
              run: |
                  cd home
                  npm run build
                  cp -r dist/. $GITHUB_WORKSPACE/release/

            - name: Audit Home
              run: |
                  cd home
                  npm audit --audit-level=critical
            
            - name: Compress out directory
              run: |
                  cd $GITHUB_WORKSPACE/release
                  zip -r $GITHUB_WORKSPACE/suvriddhi.zip .

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: build-${{ github.run_number }}
                  name: Build ${{ github.run_number }}
                  files: suvriddhi.zip
                  token: ${{ secrets.GITHUB_TOKEN }}
